version: "3.1"

services:

  ipfs:
    image: ipfs/go-ipfs:v0.8.0
    container_name: ipfs
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    volumes:
      - .ipfs_data:/data/ipfs
      - .ipfs:/ipfs/config
    environment:
      IPFS_SWARM_KEY_FILE: /ipfs/config/swarm.key
    entrypoint: []
    command: sh -c "/ipfs/config/start_ipfs daemon --migrate --enable-pubsub-experiment"

  runtime:
    image: tearust/runtime:0.14.1
    container_name: runtime
    volumes:
      - .actors:/actors
    environment:
      CLIENT_HOST: client
      RUST_BACKTRACE: full
      MALLOC_CONF: prof:true
      RUST_LOG: INFO,wasmer=WARN,regalloc2=WARN

  # ################ Parent Instance Client ##############
  client:
    image: tearust/parent-instance-client:0.14.1
    container_name: client
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8000:8000
      - 5998:5998
    volumes:
      - .tokenstate:/tokenstate
      - .libp2p:/libp2p
      - ./data:/tearust/data
    environment:
      ENCLAVE_HOST: runtime
      SELF_HOST: client
      GENESIS_CONFIG_PATH: /tearust/data/genesis.json
      TEA_ID: "${TEA_ID}"
      MACHINE_OWNER: "${MACHINE_OWNER}"
      LIBP2P_NODE_KEY_PATH: /libp2p/key
      LIBP2P_BOOTNODES: 
        /ip4/167.99.209.150/tcp/5998/p2p/12D3KooWKUd6bwsqNKzFgeruvk7pNSMUoBcrUKKU9Djqd1A3H9q8
        /ip4/146.190.233.133/tcp/5998/p2p/12D3KooWKExtVZ4AY1L3ZkMjihkf7tYPBQQ1Z3kTbUjwBGPrrQa3
      LIBP2P_SUPPORTED_PROTOCOLS: tea-0.14
      LIBP2P_AGENT_PROTOCOL: tea-0.14
      LIBP2P_VERSION: 0.14
      STATE_MAGIC_NUMBER: 100
      PERSIST_PATH: /tokenstate/persist
      ACTOR_DOWNLOAD_PATH: /actors/download
      IPFS_URL_BASE: http://host.docker.internal:5001
      RUST_BACKTRACE: full

      WAIT_HOSTS: runtime:5005, ipfs:5001
      WAIT_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

