version: "3.1"

services:
  ipfs:
    image: ipfs/go-ipfs:v0.8.0
    container_name: ipfs
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    volumes:
      - .ipfs_data:/data/ipfs
      - .ipfs:/ipfs/config
    environment:
      IPFS_SWARM_KEY_FILE: /ipfs/config/swarm.key
    entrypoint: []
    command: sh -c "/ipfs/config/start_ipfs daemon --migrate --enable-pubsub-experiment"


  # ################ Simulator  ##############
  nsm-simulator:
    image: tearust/nsm-simulator:0.11.0
    container_name: nsm-simulator
    ports:
      - 5999:5999

  # ################ Runtime  ##############
  runtime:
    image: tearust/runtime:0.11.15
    container_name: runtime
    environment:
      SIM_CLIENT_URL: http://nsm-simulator:5999
      CLIENT_HOST: client
      RUST_BACKTRACE: full

      WAIT_HOSTS: nsm-simulator:5999
      WAIT_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5

  # ################ Parent Instance Client ##############
  client:
    image: tearust/parent-instance-client:0.11.2
    container_name: client
    ports:
      - 8000:8000
      - 5998:5998
    volumes:
      - .tokenstate:/tokenstate
      - .libp2p:/libp2p
      - ./data:/tearust/data
      - ./data/manifest.yaml:/tearust/manifest.yaml
    environment:
      ENCLAVE_HOST: runtime
      SELF_HOST: client
      GENESIS_CONFIG_PATH: /tearust/data/genesis.json
      TEA_ID: "${TEA_ID}"
      MACHINE_OWNER: "${MACHINE_OWNER}"
      LIBP2P_NODE_KEY_PATH: /libp2p/key
      LIBP2P_BOOTNODES: 
        /ip4/178.62.253.136/tcp/5998
        /ip4/188.166.8.79/tcp/5998
        /ip4/167.99.209.150/tcp/5998
        /ip4/146.190.233.133/tcp/5998
        /ip4/206.189.100.29/tcp/5998
      LIBP2P_VERSION: "local0.1"
      STATE_MAGIC_NUMBER: 100
      PERSIST_PATH: /tokenstate/persist
      IP_ADDRESS: ${IP_ADDRESS}
      RUST_BACKTRACE: full

      WAIT_HOSTS: runtime:5005
      WAIT_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
