version: "3.1"

services:
  layer1:
    image: tearust/tea-camellia:fast-0.8.0
    container_name: delegate-layer1
    network_mode: host
    volumes:
      - .layer1:/root/.local
      - ./data:/tea-camellia
    command: bash -c "tea-camellia 
                      --chain canary 
                      --genesis-seed fast-0.8.0
                      --initial-validator-count 7
                      --ws-max-connections 10000 
                      -lparity_ws=warn
                      --unsafe-ws-external 
                      --rpc-cors all 
                      --genesis-coupons-path /tea-camellia/epoch8.csv 
                      --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0'
                      --bootnodes /ip4/64.227.105.212/tcp/30333/p2p/12D3KooWJmnKbzwcKiiDECeMLmRqRnK8JHqgvy6qoWNfBmnrRE7H
                      --bootnodes /ip4/164.90.159.26/tcp/30333/p2p/12D3KooWETBHFSFoMMX8YSSc2VuADhViya4z4XJteC1PQPzErL4H"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
