version: "3.1"

networks:
  default:
    external:
      name: single-network

services:
  ##################    Layer1   #######################
  layer1:
    image: tearust/tea-camellia:0.8.15
    container_name: delegate-layer1
    ports:
      - 9944:9944
      - 9933:9933
      - 30333:30333
    volumes:
      - .layer1:/root/.local
      - ./data:/tea-camellia
    command: bash -c "tea-camellia 
                      --chain canary 
                      --genesis-seed 0.8.15.3
                      --initial-validator-count 5
                      --ws-max-connections 10000 
                      -lparity_ws=warn
                      --unsafe-ws-external 
                      --rpc-cors all 
                      --no-mdns
                      --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0'
                      --bootnodes /ip4/159.89.149.143/tcp/30333/p2p/12D3KooWNPLdCwQjECGwic2sREKz4SbkFu6yxZqsuH9zE86spBtB"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
