version: "3.1"

services:
  runtime:
    image: tearust/runtime:0.13.2
    container_name: runtime
    environment:
      CLIENT_HOST: client
      RUST_BACKTRACE: full
      MALLOC_CONF: prof:true
      RUST_LOG: INFO,wasmer=WARN,regalloc2=WARN

  # ################ Parent Instance Client ##############
  client:
    image: tearust/parent-instance-client:0.13.3
    container_name: client
    ports:
      - 8000:8000
      - 5998:5998
    volumes:
      - .tokenstate:/tokenstate
      - .libp2p:/libp2p
      - ./data:/tearust/data
    environment:
      ENCLAVE_HOST: runtime
      SELF_HOST: client
      GENESIS_CONFIG_PATH: /tearust/data/genesis.json
      TEA_ID: "${TEA_ID}"
      MACHINE_OWNER: "${MACHINE_OWNER}"
      LIBP2P_NODE_KEY_PATH: /libp2p/key
      LIBP2P_BOOTNODES: 
        /ip4/147.182.197.213/tcp/5998/p2p/12D3KooWKUd6bwsqNKzFgeruvk7pNSMUoBcrUKKU9Djqd1A3H9q8
        /ip4/164.92.124.121/tcp/5998/p2p/12D3KooWKExtVZ4AY1L3ZkMjihkf7tYPBQQ1Z3kTbUjwBGPrrQa3
      LIBP2P_SUPPORTED_PROTOCOLS: tea-0.13
      LIBP2P_AGENT_PROTOCOL: tea-0.13
      LIBP2P_VERSION: 1.0
      STATE_MAGIC_NUMBER: 100
      PERSIST_PATH: /tokenstate/persist
      RUST_BACKTRACE: full

      WAIT_HOSTS: runtime:5005
      WAIT_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
