version: "3.1"

networks:
  single-network:
  single-internal:
    internal: true
services:
  ##################    Layer1   #######################
  layer1:
    image: tearust/tea-camellia:epoch7-0.8
    container_name: delegate-layer1
    ports:
      - 9944:9944
      - 9933:9933
      - 30333:30333
    volumes:
      - .layer1:/root/.local
      - ./data:/tea-camellia
    command: bash -c "tea-camellia 
                      --chain canary 
                      --genesis-seed epoch7-0.8
                      --initial-validator-count 2
                      --ws-max-connections 10000 
                      --unsafe-ws-external 
                      --rpc-cors all 
                      --genesis-coupons-path /tea-camellia/epoch5.csv 
                      --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0'
                      --bootnodes /ip4/64.227.105.212/tcp/30333/p2p/12D3KooWHEAWUN2wSaqy3mp8t2yk1AXx1BAAr6YKkegdafamTsVt
                      --bootnodes /ip4/164.90.159.26/tcp/30333/p2p/12D3KooWKcDFKHktfZ3JYaXHtMGoNEYsjrwKRBpimk4ARBvhgtwY"
    networks:
      - single-network
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

  #####################   IPFS     #####################

  ipfs:
    image: ipfs/go-ipfs:v0.8.0
    container_name: delegate-ipfs
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    volumes:
      - .ipfs_data:/data/ipfs
      - .ipfs:/ipfs/config
    environment:
      IPFS_SWARM_KEY_FILE: /ipfs/config/swarm.key
    entrypoint: []
    command: sh -c "/ipfs/config/start_ipfs daemon --migrate --enable-pubsub-experiment"
    networks:
      - single-network
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

  #####################   Orbit     ##################### 
  orbitdb:
    image: tearust/tea-orbit-db-http-api:v0.0.13
    container_name: delegate-orbitdb
    depends_on: 
      - "ipfs"
    restart: always
    ports:
      - 6001:6001
    env_file: .env
    volumes:
      - .orbitdb:/orbitdb
    command: ["node", "--max-old-space-size=512", "src/cli.js", "api", "--orbitdb-dir", "/orbitdb", "--no-https", "--http1", "--api-port", "6001"]
    environment: 
      - IPFS_HOST=ipfs
      - IPFS_PORT=5001
      - SEED=${SEED}
      - ADMIN_LIST=${ADMIN_LIST}
      - NONCE=epoch7-0.1
      - GLOBAL_BBS_DB=test
    networks:
      - single-network
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

  # ################ Adapter  ##############

  adapter:
    image: tearust/adapter:epoch5-0.4
    container_name: "delegate-adapter"
    depends_on: 
      - "orbitdb"
    ports:
      - 8000:8000
      - 5011:5011
    environment:
      IPFS_PORT: 5001
      IPFS_SERVER: ipfs
      RPC_CLIENTURL: http://parent-instance-client:5010
      WAIT_HOSTS: ipfs:5001
      WAIT_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
      ORBITDB_SERVER: orbitdb
      ORBITDB_PORT: 6001
      LAYER1_WALLET: https://wallet.teaproject.org
    networks:
      - single-network
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

  # ################ Simulator  ##############
  nsm-simulator:
    image: tearust/nsm-simulator:epoch7-0.1
    container_name: "delegate-nsm"
    ports:
      - 5999:5999
    networks:
      - single-internal
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

  # ################ Runtime  ##############
  runtime:
    image: tearust/runtime:epoch7-0.9
    container_name: "delegate-runtime"
    networks:
      - single-internal
    environment:
      VMH_HOST: vmh-server
      SIM_CLIENT_URL: http://nsm-simulator:5999
      WAIT_HOSTS: nsm-simulator:5999
      WAIT_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

  vmh-server:
    image: tearust/vmh-server:epoch7-0.4
    container_name: "delegate-vmh"
    networks:
      - single-network
      - single-internal
    environment:
      CLIENT_HOST: parent-instance-client
      ENCLAVE_HOST: runtime
      WAIT_HOSTS: runtime:5006
      WAIT_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

  parent-instance-client:
    image: tearust/parent-instance-client:epoch7-0.6
    container_name: "delegate-client"
    networks:
      - single-network
    volumes:
      - .log:/log
    # make sure 5998 port is available on server
    ports:
      - 5998:5998
    environment:
      ADAPTER_CLIENT_URL: http://adapter:5011
      LOG_FILE: /log/output.log
      VMH_HOST: vmh-server
      IPFS_HOST: ipfs
      IPFS_PORT: 5001
      TEA_ID: 3zjLTxJHkEHI6NI4EJ7yoVCwF/OCIG4k/uky5jfC23s=
      TEA_ENV_SETTINGS:
        MODE:DEV
        PUBLIC_URLS:https://tearust.com
        FLUENCER_HTTP_MODE:leader-only
      LAYER1_NODE_IP: layer1
      LAYER1_NODE_PORT: 9944
      LAYER1_ACCOUNT: //Alice
      ORBITDB_IP: orbitdb
      ORBITDB_PORT: 6001
      LIBP2P_ADDRESS: /ip4/138.68.21.103/tcp/5998
      LIBP2P_BOOTNODES: 
        /ip4/138.68.21.103/tcp/5998
        /ip4/138.68.247.206/tcp/5998
      WAIT_HOSTS: vmh-server:5007, adapter:8000, ipfs:5001, layer1:9944
      WAIT_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

    # entrypoint: /bin/bash
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
